baseURL = "https://hzreal.github.io/" # Must end with splash
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

staticDir = ["static", "themes/Niello/static"]

theme = "Niello"

[languages]
[languages.en]
title = "{CodeTrace} - Discover Issues, Share Solutions."
languageCode = "en-us"
LanguageName = "🇺🇸EN"
contentDir = "content/en"
weight = 1
[[languages.en.menus.main]]
name = 'Home'
pageRef = '/'
weight = 1
[[languages.en.menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 2
[[languages.en.menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 3
[[languages.en.menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 4
[languages.zh]
title = "{码途轨迹} - 发现问题，分享解决."
languageCode = "zh-cn"
LanguageName = "🇨🇳CN"
contentDir = "content/zh"
weight = 2
[[languages.zh.menus.main]]
name = '首页'
pageRef = '/'
weight = 1
[[languages.zh.menus.main]]
name = '文章分类'
pageRef = '/categories'
weight = 2
[[languages.zh.menus.main]]
name = '标签'
pageRef = '/tags'
weight = 3
[[languages.zh.menus.main]]
name = '个人中心'
pageRef = '/profile'
weight = 4

[params]
[params.google]
google_ad_client = "ca-pub-******"  #Optional, replace ca-pub-****** with your content
ga4 = "G-******" #Optional, replace G-****** with your Google Analytics GA4
[params.bannershowcase]
categories = ["AI"]
limit = 2
[params.email]
contact = "hzreal0823@outlook.com"
[params.ignore]
categories = ["privacy", "terms", "archives", "cookie"]
[params.license]
copyright = "&#xA9; 2019 ~ 2025 by Nico. All Rights Reserved."
[params.share]
sharethis = "******"  # Optional, Add hou ShareThis appid here
[params.disqus]
shortname = "******"    # Optional, Disqus Short Name

[outputs]
home = ["HTML", "JSON"]
